apiVersion: v1
data:
  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: ebed97fd-fa0d-41f8-9811-2558b9252555
  APPDYNAMICS_CONTROLLER_HOST_NAME: saas.appdynamics.com
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  EVENT_ENDPOINT: https://analytics.api.appdynamics.com
  APPDYNAMICS_SIM_ENABLED: "true"
  APPDYNAMICS_DOCKER_ENABLED: "false"
  APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID: "false" #optional
  APPDYNAMICS_MACHINE_HIERARCHY_PATH: "" #optional
  APPDYNAMICS_AGENT_UNIQUE_HOST_ID: "" #optional
  APPDYNAMICS_AGENT_PROXY_HOST: "" #optional
  APPDYNAMICS_AGENT_PROXY_PORT: "" #optional
  APPDYNAMICS_AGENT_PROXY_USER: "" #optional
  APPDYNAMICS_AGENT_PROXY_PASS: "" #optional
  APPDYNAMICS_AGENT_METRIC_LIMIT: "" #optional
kind: ConfigMap
metadata:
  name: ma-config
