apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: appd-infra-agent
spec: 
  template: 
    metadata: 
      labels: 
        name: appd-infra-agent
    spec:
      hostIPC: true
      hostNetwork: true
      serviceAccountName: appdynamics-infraviz
      containers:
      - name: appd-netviz-agent
        image: appdynamics/machine-agent-netviz:latest
        resources:
          requests:
            memory: "150Mi"
            cpu: "0.1"
          limits:
            memory: "250Mi"
            cpu: "0.2"
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        ports:
        - containerPort: 3892
          hostPort: 3892
        volumeMounts:
        - name: netviz-volume
          mountPath: /netviz-agent/conf/agent_config.lua
          subPath: agent_config.lua
      - name: appd-infra-agent
        image: appdynamics/machine-agent-analytics:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: controller-key
              name: cluster-agent-secret
        envFrom:
        - configMapRef:
            name: ma-config
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "0.3"
            memory: "400M"
          requests:
            cpu: "0.2"
            memory: "300M"
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: ma-log-volume
          mountPath: /opt/appdynamics/conf/logging/log4j.xml
          subPath: log4j.xml
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
      restartPolicy: Always
      volumes:
      - name: netviz-volume
        configMap:
          name: netviz-config
      - name: ma-log-volume
        configMap:
          name: ma-log-config
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
